[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.install]
cmds = ["dotnet restore Shopzee.API.csproj"]

[phases.build]
cmds = ["dotnet publish Shopzee.API.csproj -c Release -o /app/publish --no-restore"]

[start]
cmd = "dotnet /app/publish/Shopzee.API.dll"