// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopzee.API.Data;

#nullable disable

namespace Shopzee.API.Data.Migrations
{
    [DbContext(typeof(ShopzeeDbContext))]
    [Migration("20260817164827_AddResellerTables")]
    partial class AddResellerTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Shopzee.API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Line2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Shopzee.API.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Shopzee.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Shopzee.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Women's Pakistani fashion",
                            IsActive = true,
                            Name = "Women",
                            Slug = "women",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Men's Pakistani fashion",
                            IsActive = true,
                            Name = "Men",
                            Slug = "men",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("Shopzee.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingLine1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingZip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shopzee.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Shopzee.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sizes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Colors = "#8FAF8F,#C9A84C,#F5F0E8",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Exquisitely crafted sage green net suit with intricate gold embroidery. Perfect for formal occasions.",
                            DiscountPercent = 22,
                            Images = "assets/images/women/women-1.png",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = true,
                            Name = "Sage Embroidered Net Suit",
                            OriginalPrice = 16000m,
                            Price = 12500m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 124,
                            SeoDescription = "Beautiful sage green embroidered net suit for formal occasions.",
                            SeoKeywords = "women suit,embroidered,formal wear",
                            SeoTitle = "Sage Green Embroidered Net Suit | Shopzee",
                            Sizes = "XS,S,M,L,XL",
                            Sku = "WF-001",
                            Slug = "sage-embroidered-net-suit",
                            Stock = 15,
                            SubCategory = "Formal",
                            Tags = "formal,embroidered,net",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Colors = "#B8A9C9,#F5F0E8,#C9A84C",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delicate lavender chiffon suit with floral embroidery.",
                            DiscountPercent = 22,
                            Images = "assets/images/women/women-2.png",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            Name = "Lavender Chiffon Ensemble",
                            OriginalPrice = 12500m,
                            Price = 9800m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 98,
                            Sizes = "XS,S,M,L,XL",
                            Sku = "WF-002",
                            Slug = "lavender-chiffon-ensemble",
                            Stock = 12,
                            SubCategory = "Semi-Formal",
                            Tags = "semi-formal,chiffon,floral",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Colors = "#F5F0E8,#C9A84C",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Regal ivory and gold bridal ensemble with heavy embroidery.",
                            Images = "assets/images/women/women-3.png",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = true,
                            Name = "Ivory Gold Bridal Luxury",
                            Price = 28000m,
                            Rating = 5.0,
                            ReviewCount = 56,
                            Sizes = "XS,S,M,L",
                            Sku = "WB-001",
                            Slug = "ivory-gold-bridal-luxury",
                            Stock = 8,
                            SubCategory = "Bridal",
                            Tags = "bridal,luxury,embroidered",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Colors = "#98D4C8,#F5F0E8",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stunning mint organza party wear with delicate floral motifs.",
                            DiscountPercent = 19,
                            Images = "assets/images/women/women-4.png",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            Name = "Mint Organza Party Wear",
                            OriginalPrice = 10500m,
                            Price = 8500m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 83,
                            Sizes = "S,M,L,XL",
                            Sku = "WP-001",
                            Slug = "mint-organza-party-wear",
                            Stock = 20,
                            SubCategory = "Party Wear",
                            Tags = "party,organza,mint",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Colors = "#F5F0E8,#E8DCC8",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic cream suit adorned with pearl and crystal embroidery.",
                            Images = "assets/images/women/women-5.png",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = true,
                            Name = "Cream Pearl Embroidered Suit",
                            Price = 15000m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 142,
                            Sizes = "XS,S,M,L,XL",
                            Sku = "WF-003",
                            Slug = "cream-pearl-embroidered-suit",
                            Stock = 10,
                            SubCategory = "Formal",
                            Tags = "formal,pearl,cream",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Colors = "#E8B4A0,#C9A84C",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Breathtaking rose gold evening gown with hand-stitched embellishments.",
                            DiscountPercent = 21,
                            Images = "assets/images/women/women-6.png",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Rose Gold Evening Gown",
                            OriginalPrice = 28000m,
                            Price = 22000m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 67,
                            Sizes = "XS,S,M,L",
                            Sku = "WE-001",
                            Slug = "rose-gold-evening-gown",
                            Stock = 6,
                            SubCategory = "Evening Wear",
                            Tags = "evening,gown,luxury",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Colors = "#40B8C4,#C9A84C,#F5F0E8",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vibrant turquoise festive suit with golden thread work.",
                            Images = "assets/images/women/women-7.png",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = true,
                            Name = "Turquoise Festive Collection",
                            Price = 11500m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 91,
                            Sizes = "S,M,L,XL,XXL",
                            Sku = "WF-004",
                            Slug = "turquoise-festive-collection",
                            Stock = 18,
                            SubCategory = "Festive",
                            Tags = "festive,turquoise,eid",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Colors = "#F5F0E8,#E8DCC8",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant cream shalwar kameez in premium cotton.",
                            DiscountPercent = 19,
                            Images = "assets/images/men/men-1.png",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = true,
                            Name = "Classic Cream Shalwar Kameez",
                            OriginalPrice = 8000m,
                            Price = 6500m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 108,
                            Sizes = "S,M,L,XL,XXL",
                            Sku = "MF-001",
                            Slug = "classic-cream-shalwar-kameez",
                            Stock = 25,
                            SubCategory = "Formal",
                            Tags = "formal,cotton,cream",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Colors = "#1A1A1A,#2C2C2C",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sophisticated midnight black kurta set with gold thread embroidery.",
                            Images = "assets/images/men/men-2.png",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = false,
                            Name = "Midnight Black Kurta Set",
                            Price = 7800m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 87,
                            Sizes = "S,M,L,XL,XXL",
                            Sku = "MP-001",
                            Slug = "midnight-black-kurta-set",
                            Stock = 15,
                            SubCategory = "Party Wear",
                            Tags = "party,black,gold-embroidery",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Colors = "#4A4A4A,#6B6560",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Contemporary charcoal grey kurta with modern cut.",
                            DiscountPercent = 21,
                            Images = "assets/images/men/men-3.png",
                            IsActive = true,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Charcoal Grey Embroidered Kurta",
                            OriginalPrice = 7000m,
                            Price = 5500m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 72,
                            Sizes = "S,M,L,XL,XXL",
                            Sku = "MS-001",
                            Slug = "charcoal-grey-embroidered-kurta",
                            Stock = 20,
                            SubCategory = "Semi-Formal",
                            Tags = "semi-formal,grey,contemporary",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Colors = "#1B3A6B,#C9A84C",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Majestic navy blue luxury suit with gold zari work.",
                            Images = "assets/images/men/men-4.png",
                            IsActive = true,
                            IsFeatured = true,
                            IsNew = true,
                            Name = "Navy Blue Luxury Suit",
                            Price = 18500m,
                            Rating = 5.0,
                            ReviewCount = 43,
                            Sizes = "S,M,L,XL",
                            Sku = "MB-001",
                            Slug = "navy-blue-luxury-suit",
                            Stock = 8,
                            SubCategory = "Bridal / Sherwani",
                            Tags = "bridal,sherwani,luxury",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Shopzee.API.Models.ResellerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResellerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ResellerProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResellerId");

                    b.ToTable("ResellerOrders");
                });

            modelBuilder.Entity("Shopzee.API.Models.ResellerOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResellerOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ResellerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SelectedColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedSize")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResellerOrderId");

                    b.ToTable("ResellerOrderItems");
                });

            modelBuilder.Entity("Shopzee.API.Models.ResellerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CNIC")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PendingEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WithdrawnAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ResellerProfiles");
                });

            modelBuilder.Entity("Shopzee.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Shopzee.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@shopzee.pk",
                            IsActive = true,
                            Name = "Admin",
                            PasswordHash = "$2a$11$ASyI7/scyHplswETufdIkOKSiOsxIMOuQTKwnJFbTEY6.GHeGJ1Nm",
                            Phone = "+92 300 0000000",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ayesha@shopzee.pk",
                            IsActive = true,
                            Name = "Ayesha Khan",
                            PasswordHash = "$2a$11$GnP8YUXSF2K0zPVYMPwQBu4u/1TE5bnoor3OU9oHxDvU3cf1jV.UG",
                            Phone = "+92 300 1234567",
                            Role = "customer"
                        });
                });

            modelBuilder.Entity("Shopzee.API.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Shopzee.API.Models.Address", b =>
                {
                    b.HasOne("Shopzee.API.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shopzee.API.Models.Cart", b =>
                {
                    b.HasOne("Shopzee.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shopzee.API.Models.CartItem", b =>
                {
                    b.HasOne("Shopzee.API.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shopzee.API.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shopzee.API.Models.Order", b =>
                {
                    b.HasOne("Shopzee.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shopzee.API.Models.OrderItem", b =>
                {
                    b.HasOne("Shopzee.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shopzee.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shopzee.API.Models.Product", b =>
                {
                    b.HasOne("Shopzee.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shopzee.API.Models.ResellerOrder", b =>
                {
                    b.HasOne("Shopzee.API.Models.ResellerProfile", "Reseller")
                        .WithMany("Orders")
                        .HasForeignKey("ResellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reseller");
                });

            modelBuilder.Entity("Shopzee.API.Models.ResellerOrderItem", b =>
                {
                    b.HasOne("Shopzee.API.Models.ResellerOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("ResellerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shopzee.API.Models.ResellerProfile", b =>
                {
                    b.HasOne("Shopzee.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shopzee.API.Models.Review", b =>
                {
                    b.HasOne("Shopzee.API.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shopzee.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shopzee.API.Models.WishlistItem", b =>
                {
                    b.HasOne("Shopzee.API.Models.Product", "Product")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shopzee.API.Models.User", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shopzee.API.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Shopzee.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shopzee.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Shopzee.API.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("Shopzee.API.Models.ResellerOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Shopzee.API.Models.ResellerProfile", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Shopzee.API.Models.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
